# http://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/

Lifecycle:
    RestartOnAppFailure: true
    AppFailureRestartDelaySeconds: 15

Logging:
    LogLevel:
        # Trace, Debug, Information, Warning, or Error
        Default: Information

# MeadowCloud:
    # Enable Logging, Events, Command + Control
    # Enabled: false

    # Enable Over-the-air Updates
    # EnableUpdates: false

    # Enable Health Metrics
    # EnableHealthMetrics: false

    # How often to send metrics to Meadow.Cloud
    # HealthMetricsIntervalMinutes: 60
